### ISSUE TITLE
Async iteration over `path.subjects`

### ISSUE THREAD

**Issue by ccolonna** [LDflex/async-iteration-handlers#137]
I'm trying to get all the argument of a given with this code:

```ts
const { PathFactory, defaultHandlers } = require('ldflex');
const { default: ComunicaEngine } = require('@ldflex/comunica');
const defaultIterationHandlers = require('@ldflex/async-iteration-handlers');
const { namedNode } = require('@rdfjs/data-model');

// The JSON-LD context for resolving properties
const context = {
  "@context": {
    "@base" : "https://raw.githubusercontent.com/polifonia-project/sonar2021_demo/develop/src/assets/data/data_v2.jsonld",
    "@vocab": "https://w3id.org/polifonia/ON/musical-performance/",
    "label": "http://www.w3.org/2000/01/rdf-schema#label",
  },

};

// remote source
const source = 'https://raw.githubusercontent.com/polifonia-project/sonar2021_demo/develop/src/assets/data/data_v2.jsonld'

// The query engine and its source
const queryEngine = new ComunicaEngine(source);

// The object that can create new paths
const path = new PathFactory({ context, queryEngine, handlers: {
  ...defaultHandlers,
  ...defaultIterationHandlers
}});

/*
JSON LD example, see also the source doc 
{
  "@graph": [
    {...
    },
    {
      "@id": "https://w3id.org/polifonia/resource/Recording/00002",
      "@type": "https://w3id.org/polifonia/ON/musical-performance/Recording",
      ...
    },
    {
    ...
*/
const graph = path.create({ subject: namedNode('@graph')})

async function getFirstElementByType(graph, type) {

  const result = graph.subjects.find(
    async subject => {
    `${await subject["@type"]}` === type
    }
  )
}

getFirstElementByType(graph, "https://w3id.org/polifonia/ON/musical-performance/Recording")
```

But I get following error:

```

/node_modules/ldflex/lib/valueUtils.js:100
  throw new Error(`Invalid object: ${value}`);
        ^

Error: Invalid object: async subject => {
    `${await subject["@type"]}` === type
    }
    at valueToTerm (/node_modules/ldflex/lib/valueUtils.js:100:9)
    at Array.map (<anonymous>)
    at apply (/node_modules/ldflex/lib/AbstractPathResolver.js:93:28)
    at Proxy.callPathFunction (/node_modules/ldflex/lib/PathProxy.js:57:14)
    at getFirstElementByType (/index.js:57:33)
    at Object.<anonymous> (/index.js:64:1)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
```

Am I doing something wrong?

**Comment by jeswr** [comment]
After running some tests of my own I think there is a bug associated with how the function call is handled. However I haven't narrowed down on whether it is in this library or in one of the core LDflex handlers.

I'll look into this more deeply when I have some more time in a week or so.

**Comment by jeswr** [comment]
Thanks again for identifying this @ccolonna - it's an issue with the docs, the 3rd import should be `const { default: defaultIterationHandlers } = require('@ldflex/async-iteration-handlers')` - I'll merge a PR to resolve this in a sec.
